name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/skyyyx/linux-ci_cd
      - run: cd linux-ci_cd && sudo docker-compose up -d --build
      
